#define IDC_PPKVER_STATIC               100
#define IDC_PPKVER_2                    101
#define IDC_PPKVER_3                    102
#define IDC_KDF_STATIC                  103
#define IDC_KDF_ARGON2ID                104
#define IDC_KDF_ARGON2I                 105
#define IDC_KDF_ARGON2D                 106
#define IDC_ARGON2_MEM_STATIC           107
#define IDC_ARGON2_MEM                  108
#define IDC_ARGON2_MEM_STATIC2          109
#define IDC_PPK_AUTO_STATIC             110
#define IDC_PPK_AUTO_YES                111
#define IDC_PPK_AUTO_NO                 112
#define IDC_ARGON2_TIME_STATIC          113
#define IDC_ARGON2_TIME                 114
#define IDC_ARGON2_PARALLEL_STATIC      115
#define IDC_ARGON2_PARALLEL             116
